version: '3.8'

services:
  app1:
    image: chltmdgh522/stdev:latest
    container_name: stdev_app1
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JAVA_OPTS=-Xmx256m -Xms128m
    depends_on:
      - redis
    networks:
      - stdev_network

  app2:
    image: chltmdgh522/stdev:latest
    container_name: stdev_app2
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JAVA_OPTS=-Xmx256m -Xms128m
    depends_on:
      - redis
    networks:
      - stdev_network

  app3:
    image: chltmdgh522/stdev:latest
    container_name: stdev_app3
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JAVA_OPTS=-Xmx256m -Xms128m
    depends_on:
      - redis
    networks:
      - stdev_network

  redis:
    image: redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - stdev_network
    volumes:
      - redis_data:/data

networks:
  stdev_network:
    driver: bridge

volumes:
  redis_data: